### ISSUE TITLE
Importing "server.js" from esm.sh fails

### ISSUE THREAD

**Issue by deckchairlabs** [brillout/react-streaming#12]
Attempting to use this library in a Deno context, with esm.sh new option of specifying external deps. I believe it's failing as there is no esm source specified for the server.js export as the client export works fine, https://esm.sh/react-streaming@0.2.15/client?external=react

https://esm.sh/react-streaming@0.2.15/server?external=react

**Comment by deckchairlabs** [comment]
Looks like esm.sh uses the module condition if it's defined for the export

https://github.com/ije/esm.sh/blob/master/server/build.go#L208

**Comment by brillout** [comment]
So there is no ‘exports’ field for targeting deno specifically? The thing
is that the ESM modules living at ‘dist/esm/’ only work for the browser
(and probably Deno) but don’t for Node.js — Node.js will fail if it
attempts to load any module living there.

So we should opt out Node.js if possible.

**Comment by deckchairlabs** [comment]
I suppose a better option would be to possible publish a deno compatible version to https://deno.land/x

**Comment by brillout** [comment]
Is there a way to automatically publish to deno.land/x when running `npm publish`?

**Comment by brillout** [comment]
Neat.

I just re-published `0.2.15`, as `0.2.16` with a tag https://github.com/brillout/react-streaming/tags.

Is there anything else that needs to be done? (PR welcome if that's something you'd be up for.)

**Comment by brillout** [comment]
I'm just seeing https://deno.land/add_module.

So I guess it wants the source files and not `dist/`, i.e. the `src/` directory as "Subdirectory". Does it work with TypeScript Node.js source files? E.g. when importing npm packages, will it work?

**Comment by brillout** [comment]
Here we are: https://deno.land/x/react_streaming@v0.2.17. Let me know if it works, it's the `src/` directory, I'm not sure if that's what Deno wants.

FYI https://github.com/brillout/react-streaming/commit/8342ebb27c6f2863518ee59c3ef355ece1e74356.

**Comment by deckchairlabs** [comment]
It's going to need a separate output unfortunately. Deno requires the file extensions in the import specifier.

I know latest typescript now supports this? And can output the relevant code etc

**Comment by brillout** [comment]
PR welcome

**Comment by brillout** [comment]
Actually, I don't think we should complexify the build process (just because Deno stubbornly doesn't want to interop with Node.js).

Let's try with esm.sh first, ideally with https://github.com/ije/esm.sh/issues/376, but we can try `import` in the meantime and see if Node.js will be ok with that.

PR welcome to add the `import` field in a way that works with Node.js.

**Comment by brillout** [comment]
`esm.sh` actually does support the `deno` export field: https://github.com/ije/esm.sh/issues/376#issuecomment-1193018559.

Which I just added https://github.com/brillout/react-streaming/commit/4b5c6b2f3857f8099b51b4303591ccb0ae1bb731, so I guess we're good?

**Comment by brillout** [comment]
Released in [0.2.18](https://github.com/brillout/react-streaming/commit/24a51bb4558df06232852144e7e314ac7cb3a61f).
