### ISSUE TITLE
Cannot call write after a stream was destroyed

### ISSUE THREAD

**Issue by JiangWeixian** [brillout/react-streaming#20]
- node: `18.16.0`
- os: `Mac`
- pnpm: `v8`
- mini reproduction: https://github.com/JiangWeixian/react-streaming/tree/test/destory
- steps:
   - `pnpm i`
   - `pnpm tsx ./server.tsx`
   - `pnpm tsx ./request.ts` and `CTRL+C`. 

Will throw this error:

```shell
Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
    at __node_internal_captureLargerStackTrace (node:internal/errors:490:5)
    at new NodeError (node:internal/errors:399:5)
    at write_ (node:_http_outgoing:880:11)
    at ServerResponse.write (node:_http_outgoing:831:15)
}
```

Maybe a fix for this:

convert this

```tsx
writableFromUser.write(chunk, encoding, callback)
```

into this

```tsx
if (!writableFromUser.destroyed) {
  writableFromUser.write(chunk, encoding, callback)
}
```

_If this is a bug, I like to open PR for this issue_

**Comment by brillout** [comment]
👍 PR welcome.
