### ISSUE TITLE
No known conditions for "./server" specifier in "react-streaming" package

### ISSUE THREAD

**Issue by AlecAivazis** [brillout/react-streaming#26]
So I am using `react-streaming` to handle the SSR bit for Houdini's react router and have run into an issue - hopefully its a quick fix.

In short, I am running into a situation where I am using vite's `ssrLoadModule` to import a file that relies on `react-streaming/server`. This causes vite to complain that `/server` isn't an exported subpath since the import is being treated as a "browser" context (presumably since the ssr flag isn't set during `dev`). If I modify the published `package.json` to include a `browser` entry for `/server` then everything works on my end. 

Is that something you would consider? If so, I'd gladly submit a PR that makes the one-line change. I just wanted to open up the conversation before doing that.

**Comment by brillout** [comment]
👍 Seems like the PR is going to be tiny, so I'd suggest you create the PR and we continue the disucssion over there. I expect the PR to be merged quickly.

Closing in favor of your upcoming PR.
