### ISSUE TITLE
Bundling into ESM modules emits additional dynamic module

### ISSUE THREAD

**Issue by tbrannam** [brillout/react-streaming#32]
When building ESM modules that are embedding react-streaming into the bundle, but keeping react, react-dom and react-dom/server as an external, an additional dynamic package that is tied to the implementation of `renderToWebStream` is generated by the packaging tool (rollup in this case).

The external module includes inlined copies of `react-dom-server-legacy.browser.production.min.js` and it's sibling files from the cjs folder.

As I am targeting the Node runtime for this use case it would seem that there is no way to avoid generating this package, and possibly leading to a problem where externally defined react-dom may be imported by the application as a peer dependency, but react-streaming might use the bundled copies built.

I think this could all be avoided if the node target excluded `renderToWebStream`.   

This is probably a really tricky question, and if it is very unclear - I will see if I can create an example environment I can share.

**Comment by brillout** [comment]
So far removing the only dynamic import left is a non-goal (for good reasons), thus I'm closing this as I'm not sure what you want is fixable.

**Comment by tbrannam** [comment]
For posterity, updating externals to also include   'react-dom/server.node',  'react-dom/server.browser' helped me make the problem more manageable.  Thanks

**Comment by brillout** [comment]
Actually, I think I found an export strategy that works for all use cases. Let me give it a try.

**Comment by brillout** [comment]
It's released. Check out the new `package.json#exports`
