### ISSUE TITLE
Allow passing async function to injectToStream

### ISSUE THREAD

**Issue by nitedani** [brillout/react-streaming#40]
Example:
```tsx
stream.injectToStream(async () => {
  const injectionsString = await something()
  return injectionsString
})
```

It would "block" the stream until the async function is resolved, while queuing other chunks in the meantime.
When the async function is resolved, it would write the resolved value to the stream, then continue with the queued chunks.

The following is not the same, the stream can close while we are waiting for `something`
```tsx
const injectionsString = await something()
stream.injectToStream(injectionsString)
```

It would be nice for https://github.com/vikejs/vike-react/pull/125, I think this is the only missing piece for the PR. It's working as-is, but can't send the last chunk for hydration, because the stream is closed.

With this implemented, I could mimic this `await` behavior: https://github.com/apollographql/apollo-client-nextjs/blob/e7a59cb26716a77bbfac659f435f89f5af8eff61/packages/client-react-streaming/src/stream-utils/createInjectionTransformStream.tsx#L104

Why `await` is needed in the linked code, is a different issue: https://github.com/apollographql/apollo-client-nextjs/issues/325

**Comment by brillout** [comment]
This is actually something I've been wondering. As soon as the stream provided by React closes, the wrapper stream (created by `react-streaming`) is closed, causing a race condition when things are injected at the end of the stream.

Passing a promise or an async function to `injectToStream()` works only if `injectToStream()` is called before React finishes. Otherwise there is still a race condition.

I wonder if there is another (more reliable?) way to tell `react-streaming` to not close the wrapper stream too early?

**Comment by brillout** [comment]
How about this:

```js
const stream = useStream()
const makeClosableAgain = stream.doNotClose()
// ...
stream.injectToStream(someChunk)
// ...
makeClosableAgain()
```

**Comment by nitedani** [comment]
I think it's not good and unpredictable because it can send someChunk too late. While we are waiting for `something`, we need to "pause" the stream and respect the order of `injectToStream` calls.


Example issue with this:
Call 1:
```ts
const stream = useStream()
const makeClosableAgain = stream.doNotClose()
const someChunk = await something() 
stream.injectToStream(someChunk)
makeClosableAgain()
```

Call 2:
```ts
const stream = useStream()
stream.injectToStream("something that depends on Call 1")
```

Actual output:
"something that depends on Call 1"
someChunk

**Comment by brillout** [comment]
Makes sense, let me see if I can implement chunks as async functions.

**Comment by brillout** [comment]
You can now pass a chunk promise. It isn't exactly what you wanted (you cannot pass an async function) because I think passing chunk promises is more accurate, but let me know if it doesn't work out.
