### ISSUE TITLE
Stream options are null using basic setup

### ISSUE THREAD

**Issue by damassi** [brillout/react-streaming#46]
Hi! I'm trying out this lib in our app, and right away things seem to throw errors. Not sure why. Using regular React 18 renderToPipeableStream things work fine. 

Using out of the box vanilla setup config:
```tsx
stream = await renderToStream(jsx)
```

I see this error: 

Error: [react-streaming@0.3.43][Bug] You stumbled upon a bug in react-streaming's source code. Reach out at https://github.com/brillout/react-streaming/issues/new and include this error stack (the error stack is usually enough to fix the problem). A maintainer will fix the bug (usually under 24 hours). Do not hesitate to reach out as it makes react-streaming more robust. 
    at renderToStream (/Users/cn/Sites/artsy/force/node_modules/react-streaming/dist/cjs/server/renderToStream.js:113:28)
    
Which points at this line of code:
```
(0, utils_1.assert)(globalObject.renderToWebStream);
```

As a test, if I set `webStream: false` I now get this error:

```
TypeError: globalObject.renderToNodeStream is not a function
    at renderToStream (/Users/cn/Sites/artsy/force/node_modules/react-streaming/dist/cjs/server/renderToStream.js:110:79)
```

If I go into the source code and log out `globalObject`, this is what's returned: 
```tsx
 { renderToNodeStream: null, renderToWebStream: null }
```

Why would both of these be null? Am I missing some setup somewhere? 

FWIW, our app is running on Node 18, but I've also tried things under Node 20 and 22, and still the same error.

**Comment by brillout** [comment]
Minimal reproduction welcome. I'll re-open then. (If you want don't want to create a minimal reproduction you can also further dig into the source code, the problematic part is fairly easy to understand.)

**Comment by brillout** [comment]
> does not seem to correctly resolve to a node-only environment, where things are being used.

Why does your environment resolves the wrong `package.json#exports`? Or can the `exports` list be improved?

> To get things to work, I had to explicitly import it from `dist` like so:

It's a brittle workaround prone to break at any time, e.g. upon internal refactors such as when `react-streaming` will move to ESM only.

The best would be to get to the bottom of this.

**Comment by damassi** [comment]
Right. And in fact we've already run into two issues trying to import directly from this path on CircleCI. Jest [cannot resolve it](https://app.circleci.com/pipelines/github/artsy/force/66378/workflows/f3dafd18-2d60-459f-9160-16ed1f72ae81/jobs/480312). 

And then later, when mocking out said path (to get the test to green), deploying our app via a docker container the app fails to launch for the same reason, but there it seems to hint at an attempt to resolve via ESM. Works fine locally on OSX. 

In our app we don't have an `exports` key in our package.json. Perhaps that's the issue?

**Comment by brillout** [comment]
I've refactored the exports fields. Try `import { renderToStream } from 'react-streaming/server'` with `0.3.43-commit-af1be3b` and let me know if that works.

**Comment by damassi** [comment]
Unfortunately still same error:

```
Error: [react-streaming@0.3.43-commit-af1be3b][Bug] You stumbled upon a bug in react-streaming's source code. Reach out at https://github.com/brillout/react-streaming/issues/new and include this error stack (the error stack is usually enough to fix the problem). A maintainer will fix the bug (usually under 24 hours). Do not hesitate to reach out as it makes react-streaming more robust. 
    at renderToStream (/Users/cn/Sites/artsy/force/node_modules/react-streaming/dist/cjs/server/renderToStream.js:113:28)
```

Though command clicking into the path I do see an update on the TS side: 

https://github.com/user-attachments/assets/7b1720ec-d567-4c0d-812b-5b04a38e686d

Worth noting that we're not compiling with TSC; we use babel + babel-preset-typescript to compile down.

**Comment by brillout** [comment]
This is the rationale of the new `"./server"` exports: https://gist.github.com/brillout/553253e27a43ccfc01ec6c38880d1360.

To which path is `"./server"` being resolved? Which tool is doing the resolving?

**Comment by damassi** [comment]
We use webpack to [build our server code](https://github.com/artsy/force/blob/main/webpack/envs/serverConfig.js#L67) with `target: "node"`, however, during development we don't invoke any bundler at all, and [run everything through `babel-register`](https://github.com/artsy/force/blob/main/src/dev.js#L1-L4) at runtime. So in instances like this, babel would be doing the resolving. I'm unsure of how that might work, as this is the first time I've run across this issue!

**Comment by brillout** [comment]
Then I guess you don't get the error at dev and you only get it at prod, correct?

It seems that Babel is picking the `"worker"` field. Why is that?

**Comment by damassi** [comment]
Unfortunately get the error during dev, but I suspect we wouldn't get it in prod (because of `target: "node"`, which, via webpack, would likely resolve the correct package when bundling.) 

We don't have any worker setup in our app at the moment, but I'll investigate a bit.

**Comment by brillout** [comment]
Ah, yeah, that makes sense. I meant the other way around (working in prod but failing in dev).

> I'll investigate a bit.

:+1:
